version: "3"
services:
  app:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017/mydb  # Cập nhật URI nếu backend dùng Mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: ./solution
    ports:
      - "3000:80"
    container_name: frontend
    restart: unless-stopped

volumes:
  mongo-data:
